name: MineSweeperPE
version: 0.1.lpk
api: 3.11.0
main: NgLamVN\minesweeper\MineSweeper
description: "A plugin that allow you to play MineSweeper in your Minecraft BE server :3"
authors: [NgLamVN, JINODK]

permissions:
  mspe.command.start:
    default: true
  mspe.command.stop:
    default: true
